@startuml
rectangle "autoware" {
  usecase "/awapi/awapi_awiv_adapter_node"
  usecase "/control/vehicle_cmd_gate"
}

rectangle "v2i control function" {
  usecase "/v2i_interface" #LightCoral
  rectangle "user-defined/in-vehicle infrastructure device" {
    node "broadcasting device"
  }
  rectangle "user-defined/infrastructure" {
    node "v2i controller[0]" as v2ictl_0
    node "v2i controller[1]" as v2ictl_1
    node "v2i controller[n]" as v2ictl_n
    node "v2i infrastructure[0]" as v2ihw_0
    node "v2i infrastructure[1]" as v2ihw_1
    node "v2i infrastructure[n]" as v2ihw_n
  }
}

rectangle "ondemand delivery reservation function" {
  rectangle "web.auto" {
    cloud "FMS (Fleet management system)" as FMS
    usecase "Agent (Interface for FMS)" as Agent
  }
  rectangle "user-defined/saas" {
    cloud "on-demand delivery apps" as DeliveryApp
  }
  usecase "/go_interface" #LightCoral
}

usecase "/autoware_state_machine" #LightCoral

rectangle "hmi control function" {
  usecase "/ad_sound_manager" #LightCoral
  usecase "/sound_voice_alarm/audio_driver" #LightCoral
  usecase "/sound_bgm/audio_driver" #LightCoral
  usecase "/ad_status_lamp_manager" #LightCoral
  usecase "/engage_button_manager" #LightCoral
  usecase "/delivery_reservation_button_manager" #LightCoral
  usecase "/engage_srv_converter" #LightCoral
  usecase "/delivery_reservation_lamp_manager" #LightCoral
  usecase "/warning_lamp_manager" #LightCoral
  usecase "/button_output_selector" #LightCoral
  usecase "/shutdown_manager" #LightCoral

  usecase "/dio_ros_driver" as (/dio_ros_driver)

  rectangle "user-defined/in-vehicle HMI devices" {
    node "speaker"
    node "ad_status_lamp"
    node "warning_lamp"
    node "emergency_lamp"
    node "delivery_reservation_lamp"
    node "engage_button"
    node "delivery_reservation_button"
  }
}

(/v2i_interface) -[hidden] (/ad_sound_manager)
(/engage_srv_converter) -[hidden] (/v2i_interface)
(/ad_sound_manager) -[hidden] (/engage_srv_converter)
(broadcasting device) -[hidden] (speaker)

(/delivery_reservation_lamp_manager) --[hidden] (delivery_reservation_lamp)
(/ad_status_lamp_manager) --[hidden] (ad_status_lamp)
(/engage_button_manager) --[hidden] (engage_button)
(/warning_lamp_manager) --[hidden] (emergency_lamp)
(/warning_lamp_manager) ---[hidden] (warning_lamp)
(/ad_sound_manager) --[hidden] (speaker)

(/awapi/awapi_awiv_adapter_node) --> (/v2i_interface) : /awapi/tmp/infrastructure_commands
(/awapi/awapi_awiv_adapter_node) <-- (/v2i_interface) : /system/v2x/virtual_traffic_light_states
(/v2i_interface) --> (broadcasting device) : v2i command\n(UDP)
(/v2i_interface) <-- (broadcasting device) : v2i status\n(UDP)
(/v2i_interface) <--- (/autoware_state_machine)

(broadcasting device) --> (v2ictl_0)
(broadcasting device) <-- (v2ictl_0)
(broadcasting device) --> (v2ictl_1)
(broadcasting device) <-- (v2ictl_1)
(broadcasting device) --> (v2ictl_n)
(broadcasting device) <-- (v2ictl_n) : wireless communication

(/autoware_state_machine) --> (/ad_status_lamp_manager)
(/ad_status_lamp_manager) --> (/dio_ros_driver) : /dio/dout0

(/delivery_reservation_button_manager) <-- (/dio_ros_driver): /dio/din1
(/button_output_selector) <-- (/delivery_reservation_button_manager)
(/autoware_state_machine) <- (/button_output_selector)
(/shutdown_manager) <- (/button_output_selector)
(/engage_button_manager) <-- (/dio_ros_driver): /dio/din0
(/engage_srv_converter) <-- (/engage_button_manager)

(/autoware_state_machine) --> (/delivery_reservation_lamp_manager)
(/shutdown_manager) --> (/delivery_reservation_lamp_manager)
(/delivery_reservation_lamp_manager) --> (/dio_ros_driver) : /dio/dout3

(/autoware_state_machine) <-- (/engage_srv_converter)
(/autoware_state_machine) --> (/engage_srv_converter) 
(/control/vehicle_cmd_gate) <-- (/autoware_state_machine) : /api/autoware/set/engage\n /api/autoware/set/start_request
(/control/vehicle_cmd_gate) --> (/autoware_state_machine) 

(/awapi/awapi_awiv_adapter_node) -[hidden] (/control/vehicle_cmd_gate)
(/awapi/awapi_awiv_adapter_node) --> (/ad_sound_manager) : /awapi/vehicle/get/status
(/autoware_state_machine) ---> (/ad_sound_manager)
(/autoware_state_machine) <--- (/ad_sound_manager)
(/ad_sound_manager) --> (/sound_voice_alarm/audio_driver)
(/ad_sound_manager) <-- (/sound_voice_alarm/audio_driver)
(/ad_sound_manager) --> (/sound_bgm/audio_driver)
(/sound_voice_alarm/audio_driver) --> (speaker)
(/sound_bgm/audio_driver) --> (speaker)

(FMS) -> (DeliveryApp)
(FMS) <- (DeliveryApp)
(FMS) --> (Agent)
(FMS) <-- (Agent)
(Agent) -> (/go_interface) : /webauto/vehicle_info
(DeliveryApp) -->  (/go_interface) : result of GET API
(DeliveryApp) <-- (/go_interface) : request of GET API\nrequest of PATCH API
(/autoware_state_machine) -> (/go_interface)
(/autoware_state_machine) <- (/go_interface)

(broadcasting device) -[hidden] (v2ictl_1)
(v2ictl_0) -[hidden] (v2ictl_1)
(v2ictl_1) -[hidden] (v2ictl_n)
(v2ictl_n) --[hidden] (/ad_sound_manager)


(v2ictl_0) --> (v2ihw_0)
(v2ictl_0) <-- (v2ihw_0)
(v2ictl_1) --> (v2ihw_1)
(v2ictl_1) <-- (v2ihw_1)
(v2ictl_n) --> (v2ihw_n)
(v2ictl_n) <-- (v2ihw_n) : GPIO communication

(/autoware_state_machine) --> (/warning_lamp_manager)
(/warning_lamp_manager) --> (/dio_ros_driver) : /dio/dout2
(/warning_lamp_manager) --> (/dio_ros_driver) : /dio/dout1

(/dio_ros_driver) --> (ad_status_lamp)
(/dio_ros_driver) --> (warning_lamp)
(/dio_ros_driver) --> (emergency_lamp)
(/dio_ros_driver) --> (delivery_reservation_lamp)
(/dio_ros_driver) <-- (engage_button)
(/dio_ros_driver) <-- (delivery_reservation_button)

(/awapi/awapi_awiv_adapter_node) --> (/autoware_state_machine) : /awapi/autoware/get/status\n/awapi/vehicle/get/status

@enduml
